// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-contact-submissions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-contact-submissions.ts
var list_contact_submissions_default = defineTool({
  name: "list_contact_submissions",
  title: "List contact submissions",
  description: "List contact form submissions from the SecureBit website, newest first. Requires the signed-in user to be a security-team admin.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many submissions to return (default 10)."),
    only_unhandled: z.boolean().optional().describe("When true, return only submissions that have not been marked as handled.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, only_unhandled }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contact_submissions").select("id, name, email, company, message, notified_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (only_unhandled) query = query.is("notified_at", null);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return {
        content: [
          {
            type: "text",
            text: "No contact submissions are visible. If you expect results, your account may not have the security-team admin role."
          }
        ],
        structuredContent: { submissions: [] }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { submissions: data }
    };
  }
});

// src/lib/mcp/tools/get-contact-submission.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_contact_submission_default = defineTool2({
  name: "get_contact_submission",
  title: "Get contact submission",
  description: "Fetch the full details of a single contact form submission by its id. Requires the signed-in user to be a security-team admin.",
  inputSchema: { id: z2.string().uuid().describe("The submission id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("contact_submissions").select("id, name, email, company, message, notified_at, created_at").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: `No submission found with id ${id}.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { submission: data }
    };
  }
});

// src/lib/mcp/tools/mark-contact-submission-handled.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var mark_contact_submission_handled_default = defineTool3({
  name: "mark_contact_submission_handled",
  title: "Mark contact submission handled",
  description: "Mark a contact form submission as handled (records the time the security team followed up). Requires the signed-in user to be a security-team admin.",
  inputSchema: {
    id: z3.string().uuid().describe("The submission id."),
    handled: z3.boolean().optional().describe("Set false to clear the handled marker again. Defaults to true.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, handled }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("contact_submissions").update({ notified_at: handled === false ? null : (/* @__PURE__ */ new Date()).toISOString() }).eq("id", id).select("id, name, email, notified_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return {
        content: [
          { type: "text", text: `Could not update submission ${id}. It may not exist, or you lack admin access.` }
        ],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0], null, 2) }],
      structuredContent: { submission: data[0] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ltyrfowtfpccyokuraoi";
var mcp_default = defineMcp({
  name: "securely-yours",
  title: "Securely Yours",
  version: "0.1.0",
  instructions: "Tools for the SecureBit security website. Use `list_contact_submissions` to review inbound enquiries from the contact form, `get_contact_submission` for full details of one enquiry, and `mark_contact_submission_handled` once the security team has followed up. Submissions contain personal data, so only security-team admins can read them.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_contact_submissions_default, get_contact_submission_default, mark_contact_submission_handled_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
